# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FvqhjmtGYE9A1f6exo_3B8mZNL56D6kp
"""

import numpy as np
import pandas as pd

df=pd.read_csv("/content/tips.csv")

df.head()

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()

df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['day']=lb.fit_transform(df['day'])
df['time']=lb.fit_transform(df['time'])

df.head(3)

x=df.drop(columns=['total_bill'], axis=1)
y=df['total_bill']

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

x_train_sc=sc.fit_transform(x_train)

x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

np.round(x_train.describe(),1)

#ordinal encoding

from sklearn.preprocessing import  OrdinalEncoder

df=pd.read_csv("/content/tips.csv")

df

df=df.drop(columns=['total_bill' , 'tip' , 'size'])

df

from sklearn.preprocessing import OrdinalEncoder

oe=OrdinalEncoder(categories=[['Male','Female'],['Yes','No'],['Sat','Sun','Thur','Fri'],['Dinner','Lunch']])

oe.fit(df)

df_new=oe.transform(df)

df_new_2=pd.DataFrame(df_new,columns=df.columns)

df_new_2

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

df_sc=sc.fit_transform(df_new_2)

df_new3=pd.DataFrame(df_sc,columns=df.columns)

np.round(df_new3.describe(),2)

#onehot Encoder

from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

df_new=ohe.fit_transform(df)

df_new

df.shape

